#!/bin/bash
argbases=$(ls ./afiles/*.arg | fzf --multi)
echo $argbases
for argbase in $argbases; do
    if [[ -f "$argbase" ]]; then
        name=$(basename $argbase ".arg")
        sed -e "s/\${JOB_NAME}/$name/gI" launch-template.sh > "runs/$name.sh"
        sbatch "runs/$name.sh"
    fi
done
